name: Prueba ejecucion de Script
run-name: Script de Python en ubuntu

on: [push]

jobs:
  execute-script-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia actions"

      - run: python --version

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: ls -al

      - name: Ejecutar script
        run: python app.py   
