name: Prueba ejecucion de Script
run-name: Script de Python en ubuntu
on: [push]
jobs:
  execute-script-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia actions"
      - run: python --version
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: ls -al
      - run: python .github/workflows/app.py