name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: echo "Hellooo world"

      - run: echo "Escribo en un archivo de texto" | tee file.txt

      - run: ls -al                                             

      - run: cat file.txt 

      - run: rm -rf file.txt   

      - run: ls -al

      - run: echo "The job is done" 
        run: echo "USERNAME = ${{ github.actor }}" >> $GITHUB_ENV
      - run: echo $PATH

      - run: python app.py
