name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hellooo world"

      - name: Crear archivo
        run: echo "Escribo en un archivo de texto" > file.txt

      - name: Listar archivos (antes de leer)
        run: ls -al

      - name: Leer archivo
        run: cat file.txt

      - name: Eliminar archivo
        run: rm -rf file.txt

      - name: Listar archivos (después de eliminar)
        run: ls -al