name: Event Triggers
run-name: Event Triggers

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'app.py'

  workflow_dispatch:

  issues:
    types: [opened, edited, closed]

  schedule:
    - cron: "0 16 * * *"   # 10 AM CST
    - cron: "0 15 * * *"   # 10 AM CDT   

jobs:
  execute-script-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia actions"

      - run: python --version

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: ls -al   

      - name: Ejecutar script
        run: python .github/workflows/app.py 
